openapi: 3.0.3
info:
  title: Shop
  version: '1.0.0'
paths: {}
components:
  schemas:
    Shop:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        address:
          type: string
        country:
          type: string
        created_at:
          type: string
          format: date-time
          example: "2024-10-11T17:37:05+00:00"
        updated_at:
          type: string
          format: date-time
          example: "2024-10-11T17:37:05+00:00"