version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_pallinotest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pallinotest
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "8889:3306"
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password

  nginx:
    image: nginx:alpine
    container_name: nginx_pallinotest
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php_pallinotest
    volumes:
      - ./src:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini  # Aggiungi questa linea
    networks:
      - backend
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8081

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: pallinotest
      DB_USERNAME: user
      DB_PASSWORD: secret

      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003

      SESSION_DRIVER: file

      PALLINO_BASE_URI: https://test.pallinolabs.it
  redis:
    image: redis:alpine
    container_name: redis_pallinotest
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
    driver: local